version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_USER: janedoe
      POSTGRES_DB: wol
    ports:
      - "5432:5432"
